#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if type nvim > /dev/null 2>&1; then
  alias vi='nvim'
fi

export PATH=$PATH:$HOME"/.config/yarn/global/node_modules/.bin"
export PATH=$PATH:/usr/local/opt/go/libexec/bin
